export const playerColors = [
  { color: 'black', set: 'core' },
  { color: 'red', set: 'core' },
  { color: 'yellow', set: 'core' },
  { color: 'green', set: 'core' },
  { color: 'blue', set: 'core' },
  { color: 'purple', set: 'core' },
  { color: 'orange', set: 'pok' },
  { color: 'pink', set: 'pok' },
];

export const playerFactions = [
  {
    name: 'The Arborec',
    shortName: 'arborec',
    set: 'core',
    colors: { green: 1.6, black: 0.1, yellow: 0.1, blue: 0.1 },
  },
  {
    name: 'The Barony of Letnev',
    shortName: 'letnev',
    set: 'core',
    colors: { red: 0.95, black: 0.8, blue: 0.1 },
  },
  {
    name: 'The Clan of Saar',
    shortName: 'saar',
    set: 'core',
    colors: { orange: 0.85, green: 0.5, yellow: 0.4 },
  },
  {
    name: 'The Embers of Muaat',
    shortName: 'muaat',
    set: 'core',
    colors: { red: 1.25, orange: 0.65 },
  },
  {
    name: 'The Emirates of Hacan',
    shortName: 'hacan',
    set: 'core',
    colors: { yellow: 1.2, orange: 0.7 },
  },
  {
    name: 'The Federation of Sol',
    shortName: 'sol',
    set: 'core',
    colors: { blue: 1.15, yellow: 0.75 },
  },
  {
    name: 'The Ghosts of Creuss',
    shortName: 'creuss',
    set: 'core',
    colors: { blue: 1.7, black: 0.1, purple: 0.1 },
  },
  {
    name: 'The L1Z1X Mindnet',
    shortName: 'l1z1x',
    set: 'core',
    colors: { black: 0.7, blue: 0.6, red: 0.6 },
  },
  {
    name: 'The Mentak Coalition',
    shortName: 'mentak',
    set: 'core',
    colors: { orange: 0.95, black: 0.5, yellow: 0.45 },
  },
  {
    name: 'The Naalu Collective',
    shortName: 'naalu',
    set: 'core',
    colors: { green: 1.15, yellow: 0.45, orange: 0.3 },
  },
  {
    name: 'The Nekro Virus',
    shortName: 'nekro',
    set: 'core',
    colors: { red: 1.75, black: 0.15 },
  },
  {
    name: "Sardakk N'orr",
    shortName: 'sardakk',
    set: 'core',
    colors: { black: 1, red: 0.9 },
  },
  {
    name: 'The Universities of Jol-Nar',
    shortName: 'jol-nar',
    set: 'core',
    colors: { blue: 1.6, purple: 0.3 },
  },
  {
    name: 'The Winnu',
    shortName: 'winnu',
    set: 'core',
    colors: { orange: 0.75, purple: 0.6, yellow: 0.55 },
  },
  {
    name: 'The Xxcha Kingdom',
    shortName: 'xxcha',
    set: 'core',
    colors: { green: 1.1, blue: 0.8 },
  },
  {
    name: 'The Yin Brotherhood',
    shortName: 'yin',
    set: 'core',
    colors: { purple: 1.05, black: 0.6, yellow: 0.25 },
  },
  {
    name: 'The Yssaril Tribes',
    shortName: 'yssaril',
    set: 'core',
    colors: { green: 0.93, yellow: 0.63, red: 0.25, black: 0.1 },
  },
  {
    name: 'The Argent Flight',
    shortName: 'argent',
    set: 'pok',
    colors: { orange: 1.6, blue: 0.15, green: 0.15 },
  },
  {
    name: 'The Empyrean',
    shortName: 'empyrean',
    set: 'pok',
    colors: { purple: 1.6, red: 0.15, pink: 0.15 },
  },
  {
    name: 'The Mahact Gene Sorcerers',
    shortName: 'mahact',
    set: 'pok',
    colors: { yellow: 1.6, purple: 0.3 },
  },
  {
    name: 'The Naaz-Rokha Alliance',
    shortName: 'naaz-rokha',
    set: 'pok',
    colors: { green: 1.6, yellow: 0.3 },
  },
  {
    name: 'The Nomad',
    shortName: 'nomad',
    set: 'pok',
    colors: { blue: 1.5, purple: 0.65 },
  },
  {
    name: 'The Titans of Ul',
    shortName: 'ul',
    set: 'pok',
    colors: { magenta: 1.9 },
  },
  {
    name: "The Vuil'Raith Cabal",
    shortName: 'vuil-raith',
    set: 'pok',
    colors: { red: 1.35, black: 0.4, pink: 0.1 },
  },
];
